** Numpy Operations **
* Array with Numpy Array both 1d and 2d 
* Array with Scalars
* Universal Array Functions


In [3]:
import numpy as np

In [4]:
my_list = range (3,20)

In [5]:
arr = np.array(my_list)

In [12]:
# generate a list using numpy functions 
array = np.arange(4,31,2)  # step size increases in steps.

In [13]:
array

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [15]:
np.zeros((5,5))  # make a 2d array using the column and row sizes. 

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones((5,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
# linespace 
np.linspace(0,7,25)  # start element, last element and number of values needed) 

array([ 0.        ,  0.29166667,  0.58333333,  0.875     ,  1.16666667,
        1.45833333,  1.75      ,  2.04166667,  2.33333333,  2.625     ,
        2.91666667,  3.20833333,  3.5       ,  3.79166667,  4.08333333,
        4.375     ,  4.66666667,  4.95833333,  5.25      ,  5.54166667,
        5.83333333,  6.125     ,  6.41666667,  6.70833333,  7.        ])

In [28]:
# creating an identity matrix 
np.eye((6))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [29]:
# this rand() gives elements that are evenly distributed between 0 and 1
np.random.rand(4,5)  # if we pass on parameter then it returns a single dimension array

array([[ 0.14141995,  0.58785238,  0.21775059,  0.64929378,  0.00302411],
       [ 0.02752089,  0.28009356,  0.34383743,  0.45862358,  0.12524651],
       [ 0.93898307,  0.41577305,  0.14466195,  0.34634013,  0.28786891],
       [ 0.76345982,  0.56374642,  0.03135029,  0.68842335,  0.64730427]])

In [32]:
# The randn() gives a range of elements that are from a standard normal distribution. 
np.random.randn(5)

array([ 1.85418118, -0.06100163, -0.0458446 ,  1.08256294,  1.04403596])

In [40]:
# for getting a set of integers in a range. 
np.random.randint(1,100, 5)

array([31, 30, 66, 54, 20])

In [51]:
ranarr = np.random.randint(0,32,25)

In [52]:
ranarr

array([ 5,  3,  6, 14,  5, 28,  1, 29, 14, 31,  0, 29,  2, 10, 21, 19, 11,
       12, 13, 19, 10, 28, 19, 10,  6])

In [53]:
ranarr.min()

0

In [54]:
ranarr.max()  

31

In [55]:
ranarr.argmax()  # index at which the max value lies.

9

In [57]:
arr = ranarr.reshape(5,5)

In [58]:
arr

array([[ 5,  3,  6, 14,  5],
       [28,  1, 29, 14, 31],
       [ 0, 29,  2, 10, 21],
       [19, 11, 12, 13, 19],
       [10, 28, 19, 10,  6]])

In [59]:
arr.min()

0

In [60]:
arr.max()

31

In [63]:
arr.argmin()

10