** Numpy Indexing and Selection ** 

In [3]:
import numpy as np 

In [13]:
arr = np.arange(0,11)

In [14]:
slice_off_arr = arr[0:5]

In [15]:
slice_off_arr

array([0, 1, 2, 3, 4])

In [16]:
slice_off_arr[:] = 99 

In [17]:
slice_off_arr

array([99, 99, 99, 99, 99])

In [18]:
arr  # the change in slice also changes the array. so we have to be aware of this pitfall.
     # if need to have 

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [4]:
arr_2d = np.array([[10,9,21],[11,43,19],[9,34,31]])

In [5]:
arr_2d[:2,1:]

array([[ 9, 21],
       [43, 19]])

In [7]:
bool_indx = arr_2d > 5   # this statement applies the condition to the all the elements and returns an array in bool.
bool_indx

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [8]:
arr_2d[bool_indx]  # this will return all values in the 2d array that have true in the corresponding elements.

array([10,  9, 21, 11, 43, 19,  9, 34, 31])

In [9]:
arr_2d[arr_2d < 11]  # short-cut notation of earlier version.

array([10,  9,  9])

In [10]:
arr_2d1 = np.arange(0,50).reshape(5,10)

In [11]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
arr_2d1[2,4:]  # We can use these slice notations that can be used to get parts of the array.

array([24, 25, 26, 27, 28, 29])