** Numpy ** is a  Linear Algebra library that is very fast as it has bindings to C libraries . 
All data science libraries use numpy as the building blocks 
Numpy  arrays are ways of using numpy and they come in two falvors . 
1. vectors  (1D)
2. metrices (2D) 


In [3]:
import numpy as np

In [4]:
my_list = [1,2,5]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 5])

In [11]:
np.arange(0,11,2) # make an array of integers range or 0,11 with step size of 2

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)  # helps create a new vector with all zeors and a size/length of 3 

array([ 0.,  0.,  0.])

In [18]:
np.linspace(0,5,20) # prepare a 1D array which give 20 elements between 0 and 5    

array([ 0.        ,  0.26315789,  0.52631579,  0.78947368,  1.05263158,
        1.31578947,  1.57894737,  1.84210526,  2.10526316,  2.36842105,
        2.63157895,  2.89473684,  3.15789474,  3.42105263,  3.68421053,
        3.94736842,  4.21052632,  4.47368421,  4.73684211,  5.        ])

In [20]:
np.random.rand(5) # create a 1D array that will have 5 random values between 0 and 1 [uniform distribution]

array([ 0.71226209,  0.71736866,  0.35900882,  0.40125496,  0.67550034])

In [23]:
np.random.randn(5) # create 1D array taht will make 5 random values which are 

array([ 0.14270312, -0.48820238,  0.66974677, -0.8349602 , -0.58747967])

In [28]:
np.random.randint(1,100, 3) # gives 3 random value between 1 and 100 

array([56, 57, 39])

** Numpy Matrix  **

In [7]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.zeros((2,3)) # create a 2d array with width 3 columns and 2 rows all initialized to 0

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.eye(4)  # create a new identity matrix of size 4x4 

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
np.random.rand(5,5) # make a 2D array with 5 rows and 5 columns with random values between 0 and 1  [uniform distribution]

array([[ 0.15927092,  0.98280751,  0.45714154,  0.52195204,  0.25890744],
       [ 0.99777019,  0.7536673 ,  0.73694753,  0.55946427,  0.40938386],
       [ 0.64838288,  0.66298527,  0.28634897,  0.63996754,  0.42793128],
       [ 0.48291637,  0.50775317,  0.7130228 ,  0.83187838,  0.85138466],
       [ 0.51233497,  0.18243204,  0.59849637,  0.39294974,  0.60690201]])

In [22]:
np.random.randn(3,5) # this will give values not form uniform distribution but normal distribution but 

array([[ 3.16317225, -0.30589526,  1.24257271,  1.31369042,  0.15257015],
       [-0.84651884,  0.05809589,  0.32835678,  1.5862731 ,  0.4718195 ],
       [-0.33076559,  1.17165853, -1.38640793, -1.06829728,  0.65650474]])

In [33]:
# exmaples for reshaping the single array to 2D array 
arr = np.arange(50)
arr = arr.reshape(5,10)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
arr.max()  # this gives the max element in the array in question this can be either a 1d or 2d array. similar .min()

49

In [ ]:
arr.argm